//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadImageEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialogs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialogs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadImageEditor.Dialogs", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string AddText_Color {
            get {
                return ResourceManager.GetString("AddText_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The color of the text to add.
        /// </summary>
        internal static string AddText_ColorToolTip {
            get {
                return ResourceManager.GetString("AddText_ColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Current Color is {0}).
        /// </summary>
        internal static string AddText_CurrentColorText {
            get {
                return ResourceManager.GetString("AddText_CurrentColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Family.
        /// </summary>
        internal static string AddText_FontFamily {
            get {
                return ResourceManager.GetString("AddText_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The font family of the text to add.
        /// </summary>
        internal static string AddText_FontFamilyToolTip {
            get {
                return ResourceManager.GetString("AddText_FontFamilyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        internal static string AddText_FontSize {
            get {
                return ResourceManager.GetString("AddText_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the text to add.
        /// </summary>
        internal static string AddText_FontSizeToolTip {
            get {
                return ResourceManager.GetString("AddText_FontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Color.
        /// </summary>
        internal static string AddText_PickColorToolTip {
            get {
                return ResourceManager.GetString("AddText_PickColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your text here....
        /// </summary>
        internal static string AddText_SampleText {
            get {
                return ResourceManager.GetString("AddText_SampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Text.
        /// </summary>
        internal static string AddText_Title {
            get {
                return ResourceManager.GetString("AddText_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Size.
        /// </summary>
        internal static string Common_ActualSize {
            get {
                return ResourceManager.GetString("Common_ActualSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Fit.
        /// </summary>
        internal static string Common_BestFit {
            get {
                return ResourceManager.GetString("Common_BestFit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constrain Proportions?.
        /// </summary>
        internal static string Common_ConstrainProportions {
            get {
                return ResourceManager.GetString("Common_ConstrainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease.
        /// </summary>
        internal static string Common_Decrease {
            get {
                return ResourceManager.GetString("Common_Decrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with a name same as the target already exists!.
        /// </summary>
        internal static string Common_FileExists {
            get {
                return ResourceManager.GetString("Common_FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Common_Height {
            get {
                return ResourceManager.GetString("Common_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase.
        /// </summary>
        internal static string Common_Increase {
            get {
                return ResourceManager.GetString("Common_Increase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Common_Insert {
            get {
                return ResourceManager.GetString("Common_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Common_Left {
            get {
                return ResourceManager.GetString("Common_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to the target folder!.
        /// </summary>
        internal static string Common_MessageCannotWriteToFolder {
            get {
                return ResourceManager.GetString("Common_MessageCannotWriteToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file could not be deleted because the application did not have enough permissions. Please, contact the administrator..
        /// </summary>
        internal static string Common_NoPermissionsToDeleteFile {
            get {
                return ResourceManager.GetString("Common_NoPermissionsToDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite if file exists?.
        /// </summary>
        internal static string Common_OverwriteExisting {
            get {
                return ResourceManager.GetString("Common_OverwriteExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        internal static string Common_Position {
            get {
                return ResourceManager.GetString("Common_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string Common_Set {
            get {
                return ResourceManager.GetString("Common_Set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to change the value.
        /// </summary>
        internal static string Common_SliderDrag {
            get {
                return ResourceManager.GetString("Common_SliderDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Width and Height.
        /// </summary>
        internal static string Common_SwapWidthHeight {
            get {
                return ResourceManager.GetString("Common_SwapWidthHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Common_Top {
            get {
                return ResourceManager.GetString("Common_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string Common_Url {
            get {
                return ResourceManager.GetString("Common_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Common_Width {
            get {
                return ResourceManager.GetString("Common_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X.
        /// </summary>
        internal static string Common_X {
            get {
                return ResourceManager.GetString("Common_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Common_Y {
            get {
                return ResourceManager.GetString("Common_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        internal static string Crop_AspectRatio {
            get {
                return ResourceManager.GetString("Crop_AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Aspect Ratio.
        /// </summary>
        internal static string Crop_AspectRatioToolTip {
            get {
                return ResourceManager.GetString("Crop_AspectRatioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        internal static string Crop_Button {
            get {
                return ResourceManager.GetString("Crop_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Image.
        /// </summary>
        internal static string Crop_Title {
            get {
                return ResourceManager.GetString("Crop_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip None.
        /// </summary>
        internal static string Flip_None {
            get {
                return ResourceManager.GetString("Flip_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip.
        /// </summary>
        internal static string Flip_Title {
            get {
                return ResourceManager.GetString("Flip_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        internal static string InsertImage_Title {
            get {
                return ResourceManager.GetString("InsertImage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value between 0 and 100%.
        /// </summary>
        internal static string Opacity_TextboxToolTip {
            get {
                return ResourceManager.GetString("Opacity_TextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity.
        /// </summary>
        internal static string Opacity_Title {
            get {
                return ResourceManager.GetString("Opacity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print_Button {
            get {
                return ResourceManager.GetString("Print_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Image.
        /// </summary>
        internal static string Print_Title {
            get {
                return ResourceManager.GetString("Print_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not delete this string..
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string Resize_Button {
            get {
                return ResourceManager.GetString("Resize_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Resize_Percentage {
            get {
                return ResourceManager.GetString("Resize_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of original Width x Height [0,100%].
        /// </summary>
        internal static string Resize_PercentageToolTip {
            get {
                return ResourceManager.GetString("Resize_PercentageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Sizes.
        /// </summary>
        internal static string Resize_PresetSizes {
            get {
                return ResourceManager.GetString("Resize_PresetSizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Preset Width x Height.
        /// </summary>
        internal static string Resize_PresetSizesToolTip {
            get {
                return ResourceManager.GetString("Resize_PresetSizesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string Resize_Title {
            get {
                return ResourceManager.GetString("Resize_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a rotation angle.
        /// </summary>
        internal static string Rotate_DropDownToolTip {
            get {
                return ResourceManager.GetString("Rotate_DropDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate.
        /// </summary>
        internal static string Rotate_Title {
            get {
                return ResourceManager.GetString("Rotate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Image.
        /// </summary>
        internal static string Save_ClientRadioText {
            get {
                return ResourceManager.GetString("Save_ClientRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        internal static string Save_FileNameLabel {
            get {
                return ResourceManager.GetString("Save_FileNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter File Name.
        /// </summary>
        internal static string Save_FileNameToolTip {
            get {
                return ResourceManager.GetString("Save_FileNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image on Server.
        /// </summary>
        internal static string Save_ServerRadioText {
            get {
                return ResourceManager.GetString("Save_ServerRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Image.
        /// </summary>
        internal static string Save_Title {
            get {
                return ResourceManager.GetString("Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to 100%.
        /// </summary>
        internal static string Zoom_ActualSizeToolTip {
            get {
                return ResourceManager.GetString("Zoom_ActualSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit image in editable area.
        /// </summary>
        internal static string Zoom_BestFitToolTip {
            get {
                return ResourceManager.GetString("Zoom_BestFitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a value between 0 and 100%.
        /// </summary>
        internal static string Zoom_TextboxToolTip {
            get {
                return ResourceManager.GetString("Zoom_TextboxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom_Title {
            get {
                return ResourceManager.GetString("Zoom_Title", resourceCulture);
            }
        }
    }
}
