//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.239
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HConnexum.Tramitador.Sitio.App_GlobalResources
{
    using System;
    
    
    /// <summary>
    ///   Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o vuelva a generar el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Tramitador {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tramitador() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Tramitador", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 93.
        /// </summary>
        internal static string afganistán {
            get {
                return ResourceManager.GetString("afganistán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 355.
        /// </summary>
        internal static string albania {
            get {
                return ResourceManager.GetString("albania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 49.
        /// </summary>
        internal static string alemania {
            get {
                return ResourceManager.GetString("alemania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 376.
        /// </summary>
        internal static string andorra {
            get {
                return ResourceManager.GetString("andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 244.
        /// </summary>
        internal static string angola {
            get {
                return ResourceManager.GetString("angola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1264.
        /// </summary>
        internal static string anguila {
            get {
                return ResourceManager.GetString("anguila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1268.
        /// </summary>
        internal static string antigua_y_barbuda {
            get {
                return ResourceManager.GetString("antigua_y_barbuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 599.
        /// </summary>
        internal static string antillas_holandesas {
            get {
                return ResourceManager.GetString("antillas_holandesas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 672.
        /// </summary>
        internal static string antártida {
            get {
                return ResourceManager.GetString("antártida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 966.
        /// </summary>
        internal static string arabia_saudí {
            get {
                return ResourceManager.GetString("arabia_saudí", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 213.
        /// </summary>
        internal static string argelia {
            get {
                return ResourceManager.GetString("argelia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 54.
        /// </summary>
        internal static string argentina {
            get {
                return ResourceManager.GetString("argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 374.
        /// </summary>
        internal static string armenia {
            get {
                return ResourceManager.GetString("armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 297.
        /// </summary>
        internal static string aruba {
            get {
                return ResourceManager.GetString("aruba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 247.
        /// </summary>
        internal static string ascension_island {
            get {
                return ResourceManager.GetString("ascension_island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 61.
        /// </summary>
        internal static string australia {
            get {
                return ResourceManager.GetString("australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 43.
        /// </summary>
        internal static string austria {
            get {
                return ResourceManager.GetString("austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 994.
        /// </summary>
        internal static string azerbaiyán {
            get {
                return ResourceManager.GetString("azerbaiyán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1242.
        /// </summary>
        internal static string bahamas {
            get {
                return ResourceManager.GetString("bahamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 973.
        /// </summary>
        internal static string bahréin {
            get {
                return ResourceManager.GetString("bahréin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 880.
        /// </summary>
        internal static string bangladesh {
            get {
                return ResourceManager.GetString("bangladesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1246.
        /// </summary>
        internal static string barbados {
            get {
                return ResourceManager.GetString("barbados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 501.
        /// </summary>
        internal static string belice {
            get {
                return ResourceManager.GetString("belice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 229.
        /// </summary>
        internal static string benín {
            get {
                return ResourceManager.GetString("benín", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1441.
        /// </summary>
        internal static string bermudas {
            get {
                return ResourceManager.GetString("bermudas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 975.
        /// </summary>
        internal static string bhután {
            get {
                return ResourceManager.GetString("bhután", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 375.
        /// </summary>
        internal static string bielorrusia {
            get {
                return ResourceManager.GetString("bielorrusia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 591.
        /// </summary>
        internal static string bolivia {
            get {
                return ResourceManager.GetString("bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 387.
        /// </summary>
        internal static string bosnia_herzegovina {
            get {
                return ResourceManager.GetString("bosnia_herzegovina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 267.
        /// </summary>
        internal static string botswana {
            get {
                return ResourceManager.GetString("botswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 55.
        /// </summary>
        internal static string brasil {
            get {
                return ResourceManager.GetString("brasil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 673.
        /// </summary>
        internal static string brunei_darussalam {
            get {
                return ResourceManager.GetString("brunei_darussalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 359.
        /// </summary>
        internal static string bulgaria {
            get {
                return ResourceManager.GetString("bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 226.
        /// </summary>
        internal static string burkina_faso {
            get {
                return ResourceManager.GetString("burkina_faso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 257.
        /// </summary>
        internal static string burundi {
            get {
                return ResourceManager.GetString("burundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 32.
        /// </summary>
        internal static string bélgica {
            get {
                return ResourceManager.GetString("bélgica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 238.
        /// </summary>
        internal static string cabo_verde {
            get {
                return ResourceManager.GetString("cabo_verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 855.
        /// </summary>
        internal static string camboya {
            get {
                return ResourceManager.GetString("camboya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 237.
        /// </summary>
        internal static string camerún {
            get {
                return ResourceManager.GetString("camerún", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string canadá {
            get {
                return ResourceManager.GetString("canadá", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 235.
        /// </summary>
        internal static string chad {
            get {
                return ResourceManager.GetString("chad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 56.
        /// </summary>
        internal static string chile {
            get {
                return ResourceManager.GetString("chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 86.
        /// </summary>
        internal static string china {
            get {
                return ResourceManager.GetString("china", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 357.
        /// </summary>
        internal static string chipre {
            get {
                return ResourceManager.GetString("chipre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 57.
        /// </summary>
        internal static string colombia {
            get {
                return ResourceManager.GetString("colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 269.
        /// </summary>
        internal static string comores {
            get {
                return ResourceManager.GetString("comores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 225.
        /// </summary>
        internal static string costa_de_marfil {
            get {
                return ResourceManager.GetString("costa_de_marfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 506.
        /// </summary>
        internal static string costa_rica {
            get {
                return ResourceManager.GetString("costa_rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 385.
        /// </summary>
        internal static string croacia {
            get {
                return ResourceManager.GetString("croacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 53.
        /// </summary>
        internal static string cuba {
            get {
                return ResourceManager.GetString("cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 45.
        /// </summary>
        internal static string dinamarca {
            get {
                return ResourceManager.GetString("dinamarca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 253.
        /// </summary>
        internal static string djibouti {
            get {
                return ResourceManager.GetString("djibouti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1767.
        /// </summary>
        internal static string dominica {
            get {
                return ResourceManager.GetString("dominica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 593.
        /// </summary>
        internal static string ecuador {
            get {
                return ResourceManager.GetString("ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 20.
        /// </summary>
        internal static string egipto {
            get {
                return ResourceManager.GetString("egipto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 503.
        /// </summary>
        internal static string el_salvador {
            get {
                return ResourceManager.GetString("el_salvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 971.
        /// </summary>
        internal static string emiratos_árabes_unidos {
            get {
                return ResourceManager.GetString("emiratos_árabes_unidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 291.
        /// </summary>
        internal static string eritrea {
            get {
                return ResourceManager.GetString("eritrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 421.
        /// </summary>
        internal static string eslovaquia {
            get {
                return ResourceManager.GetString("eslovaquia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 386.
        /// </summary>
        internal static string eslovenia {
            get {
                return ResourceManager.GetString("eslovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 34.
        /// </summary>
        internal static string españa {
            get {
                return ResourceManager.GetString("españa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 691.
        /// </summary>
        internal static string estados_federados_de_micronesia {
            get {
                return ResourceManager.GetString("estados_federados_de_micronesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string estados_unidos {
            get {
                return ResourceManager.GetString("estados_unidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 372.
        /// </summary>
        internal static string estonia {
            get {
                return ResourceManager.GetString("estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 79.
        /// </summary>
        internal static string esvalbard_y_jan_mayen {
            get {
                return ResourceManager.GetString("esvalbard_y_jan_mayen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 251.
        /// </summary>
        internal static string etiopía {
            get {
                return ResourceManager.GetString("etiopía", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 679.
        /// </summary>
        internal static string fiji {
            get {
                return ResourceManager.GetString("fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 63.
        /// </summary>
        internal static string filipinas {
            get {
                return ResourceManager.GetString("filipinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 358.
        /// </summary>
        internal static string finlandia {
            get {
                return ResourceManager.GetString("finlandia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 33.
        /// </summary>
        internal static string francia {
            get {
                return ResourceManager.GetString("francia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 241.
        /// </summary>
        internal static string gabón {
            get {
                return ResourceManager.GetString("gabón", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 220.
        /// </summary>
        internal static string gambia {
            get {
                return ResourceManager.GetString("gambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 995.
        /// </summary>
        internal static string georgia {
            get {
                return ResourceManager.GetString("georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 233.
        /// </summary>
        internal static string ghana {
            get {
                return ResourceManager.GetString("ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 350.
        /// </summary>
        internal static string gibraltar {
            get {
                return ResourceManager.GetString("gibraltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1473.
        /// </summary>
        internal static string granada {
            get {
                return ResourceManager.GetString("granada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30.
        /// </summary>
        internal static string grecia {
            get {
                return ResourceManager.GetString("grecia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 299.
        /// </summary>
        internal static string groenlandia {
            get {
                return ResourceManager.GetString("groenlandia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 590.
        /// </summary>
        internal static string guadalupe {
            get {
                return ResourceManager.GetString("guadalupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1671.
        /// </summary>
        internal static string guam {
            get {
                return ResourceManager.GetString("guam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 502.
        /// </summary>
        internal static string guatemala {
            get {
                return ResourceManager.GetString("guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44.
        /// </summary>
        internal static string guernsey {
            get {
                return ResourceManager.GetString("guernsey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 224.
        /// </summary>
        internal static string guinea {
            get {
                return ResourceManager.GetString("guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 245.
        /// </summary>
        internal static string guinea_bisáu {
            get {
                return ResourceManager.GetString("guinea_bisáu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 240.
        /// </summary>
        internal static string guinea_ecuatorial {
            get {
                return ResourceManager.GetString("guinea_ecuatorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 594.
        /// </summary>
        internal static string guinea_francesa {
            get {
                return ResourceManager.GetString("guinea_francesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 592.
        /// </summary>
        internal static string guyana {
            get {
                return ResourceManager.GetString("guyana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 509.
        /// </summary>
        internal static string haití {
            get {
                return ResourceManager.GetString("haití", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 504.
        /// </summary>
        internal static string honduras {
            get {
                return ResourceManager.GetString("honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 852.
        /// </summary>
        internal static string hong_kong {
            get {
                return ResourceManager.GetString("hong_kong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 36.
        /// </summary>
        internal static string hungría {
            get {
                return ResourceManager.GetString("hungría", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 91.
        /// </summary>
        internal static string india {
            get {
                return ResourceManager.GetString("india", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 62.
        /// </summary>
        internal static string indonesia {
            get {
                return ResourceManager.GetString("indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 964.
        /// </summary>
        internal static string irak {
            get {
                return ResourceManager.GetString("irak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 353.
        /// </summary>
        internal static string irlanda {
            get {
                return ResourceManager.GetString("irlanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 98.
        /// </summary>
        internal static string irán {
            get {
                return ResourceManager.GetString("irán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 354.
        /// </summary>
        internal static string islandia {
            get {
                return ResourceManager.GetString("islandia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1345.
        /// </summary>
        internal static string islas_caimán {
            get {
                return ResourceManager.GetString("islas_caimán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 61.
        /// </summary>
        internal static string islas_cocos {
            get {
                return ResourceManager.GetString("islas_cocos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 682.
        /// </summary>
        internal static string islas_cook {
            get {
                return ResourceManager.GetString("islas_cook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1670.
        /// </summary>
        internal static string islas_de_norte_mariana {
            get {
                return ResourceManager.GetString("islas_de_norte_mariana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 298.
        /// </summary>
        internal static string islas_faroe {
            get {
                return ResourceManager.GetString("islas_faroe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 500.
        /// </summary>
        internal static string islas_malvinas {
            get {
                return ResourceManager.GetString("islas_malvinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 692.
        /// </summary>
        internal static string islas_marshall {
            get {
                return ResourceManager.GetString("islas_marshall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 672.
        /// </summary>
        internal static string islas_norfolk {
            get {
                return ResourceManager.GetString("islas_norfolk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 677.
        /// </summary>
        internal static string islas_salomón {
            get {
                return ResourceManager.GetString("islas_salomón", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1649.
        /// </summary>
        internal static string islas_turks_y_caicos {
            get {
                return ResourceManager.GetString("islas_turks_y_caicos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 808.
        /// </summary>
        internal static string islas_ultramarinas_de_estados_unidos {
            get {
                return ResourceManager.GetString("islas_ultramarinas_de_estados_unidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1284.
        /// </summary>
        internal static string islas_vírgenes_británicas {
            get {
                return ResourceManager.GetString("islas_vírgenes_británicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1340.
        /// </summary>
        internal static string islas_vírgenes_estadounidenses {
            get {
                return ResourceManager.GetString("islas_vírgenes_estadounidenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 61.
        /// </summary>
        internal static string isla_navidad {
            get {
                return ResourceManager.GetString("isla_navidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44.
        /// </summary>
        internal static string isle_of_man {
            get {
                return ResourceManager.GetString("isle_of_man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 972.
        /// </summary>
        internal static string israel {
            get {
                return ResourceManager.GetString("israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 39.
        /// </summary>
        internal static string italia {
            get {
                return ResourceManager.GetString("italia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1876.
        /// </summary>
        internal static string jamaica {
            get {
                return ResourceManager.GetString("jamaica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 81.
        /// </summary>
        internal static string japón {
            get {
                return ResourceManager.GetString("japón", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44.
        /// </summary>
        internal static string jersey {
            get {
                return ResourceManager.GetString("jersey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 962.
        /// </summary>
        internal static string jordania {
            get {
                return ResourceManager.GetString("jordania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        internal static string kazajstán {
            get {
                return ResourceManager.GetString("kazajstán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 254.
        /// </summary>
        internal static string kenia {
            get {
                return ResourceManager.GetString("kenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 996.
        /// </summary>
        internal static string kirguistán {
            get {
                return ResourceManager.GetString("kirguistán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 686.
        /// </summary>
        internal static string kiribati {
            get {
                return ResourceManager.GetString("kiribati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 965.
        /// </summary>
        internal static string kuwait {
            get {
                return ResourceManager.GetString("kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 266.
        /// </summary>
        internal static string Lesoto {
            get {
                return ResourceManager.GetString("Lesoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 371.
        /// </summary>
        internal static string Letonia {
            get {
                return ResourceManager.GetString("Letonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 961.
        /// </summary>
        internal static string Libano {
            get {
                return ResourceManager.GetString("Libano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 231.
        /// </summary>
        internal static string Liberia {
            get {
                return ResourceManager.GetString("Liberia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 218.
        /// </summary>
        internal static string Libia {
            get {
                return ResourceManager.GetString("Libia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 41.
        /// </summary>
        internal static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 370.
        /// </summary>
        internal static string Lituania {
            get {
                return ResourceManager.GetString("Lituania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 352.
        /// </summary>
        internal static string Luxemburgo {
            get {
                return ResourceManager.GetString("Luxemburgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 853.
        /// </summary>
        internal static string macao {
            get {
                return ResourceManager.GetString("macao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 389.
        /// </summary>
        internal static string macedonia {
            get {
                return ResourceManager.GetString("macedonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 261.
        /// </summary>
        internal static string madagascar {
            get {
                return ResourceManager.GetString("madagascar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 60.
        /// </summary>
        internal static string malasia {
            get {
                return ResourceManager.GetString("malasia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 265.
        /// </summary>
        internal static string malawi {
            get {
                return ResourceManager.GetString("malawi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 960.
        /// </summary>
        internal static string maldivas {
            get {
                return ResourceManager.GetString("maldivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 356.
        /// </summary>
        internal static string malta {
            get {
                return ResourceManager.GetString("malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 223.
        /// </summary>
        internal static string malí {
            get {
                return ResourceManager.GetString("malí", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 212.
        /// </summary>
        internal static string marruecos {
            get {
                return ResourceManager.GetString("marruecos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 596.
        /// </summary>
        internal static string martinica {
            get {
                return ResourceManager.GetString("martinica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 230.
        /// </summary>
        internal static string mauricio {
            get {
                return ResourceManager.GetString("mauricio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 222.
        /// </summary>
        internal static string mauritania {
            get {
                return ResourceManager.GetString("mauritania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 269.
        /// </summary>
        internal static string mayote {
            get {
                return ResourceManager.GetString("mayote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 373.
        /// </summary>
        internal static string moldavia {
            get {
                return ResourceManager.GetString("moldavia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 976.
        /// </summary>
        internal static string mongolia {
            get {
                return ResourceManager.GetString("mongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1664.
        /// </summary>
        internal static string montserrat {
            get {
                return ResourceManager.GetString("montserrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 258.
        /// </summary>
        internal static string mozambique {
            get {
                return ResourceManager.GetString("mozambique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 95.
        /// </summary>
        internal static string myanmar {
            get {
                return ResourceManager.GetString("myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 52.
        /// </summary>
        internal static string méxico {
            get {
                return ResourceManager.GetString("méxico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 377.
        /// </summary>
        internal static string mónaco {
            get {
                return ResourceManager.GetString("mónaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 264.
        /// </summary>
        internal static string namibia {
            get {
                return ResourceManager.GetString("namibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 674.
        /// </summary>
        internal static string nauru {
            get {
                return ResourceManager.GetString("nauru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 977.
        /// </summary>
        internal static string nepal {
            get {
                return ResourceManager.GetString("nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 505.
        /// </summary>
        internal static string nicaragua {
            get {
                return ResourceManager.GetString("nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 234.
        /// </summary>
        internal static string nigeria {
            get {
                return ResourceManager.GetString("nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 683.
        /// </summary>
        internal static string niue {
            get {
                return ResourceManager.GetString("niue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 47.
        /// </summary>
        internal static string noruega {
            get {
                return ResourceManager.GetString("noruega", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 687.
        /// </summary>
        internal static string nueva_caledonia {
            get {
                return ResourceManager.GetString("nueva_caledonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 64.
        /// </summary>
        internal static string nueva_zelanda {
            get {
                return ResourceManager.GetString("nueva_zelanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 227.
        /// </summary>
        internal static string níger {
            get {
                return ResourceManager.GetString("níger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 968.
        /// </summary>
        internal static string omán {
            get {
                return ResourceManager.GetString("omán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 92.
        /// </summary>
        internal static string pakistán {
            get {
                return ResourceManager.GetString("pakistán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 680.
        /// </summary>
        internal static string palau {
            get {
                return ResourceManager.GetString("palau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 970.
        /// </summary>
        internal static string palestina {
            get {
                return ResourceManager.GetString("palestina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 507.
        /// </summary>
        internal static string panamá {
            get {
                return ResourceManager.GetString("panamá", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 675.
        /// </summary>
        internal static string papúa_nueva_guinea {
            get {
                return ResourceManager.GetString("papúa_nueva_guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 595.
        /// </summary>
        internal static string paraguay {
            get {
                return ResourceManager.GetString("paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 31.
        /// </summary>
        internal static string países_bajos {
            get {
                return ResourceManager.GetString("países_bajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 51.
        /// </summary>
        internal static string perú {
            get {
                return ResourceManager.GetString("perú", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 872.
        /// </summary>
        internal static string pitcairn {
            get {
                return ResourceManager.GetString("pitcairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 689.
        /// </summary>
        internal static string polinesia_francesa {
            get {
                return ResourceManager.GetString("polinesia_francesa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 48.
        /// </summary>
        internal static string polonia {
            get {
                return ResourceManager.GetString("polonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 351.
        /// </summary>
        internal static string portugal {
            get {
                return ResourceManager.GetString("portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1.
        /// </summary>
        internal static string puerto_rico {
            get {
                return ResourceManager.GetString("puerto_rico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 974.
        /// </summary>
        internal static string qatar {
            get {
                return ResourceManager.GetString("qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44.
        /// </summary>
        internal static string reino_unido {
            get {
                return ResourceManager.GetString("reino_unido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44.
        /// </summary>
        internal static string reino_unido1 {
            get {
                return ResourceManager.GetString("reino_unido1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 236.
        /// </summary>
        internal static string república_centroafricana {
            get {
                return ResourceManager.GetString("república_centroafricana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 420.
        /// </summary>
        internal static string república_checa {
            get {
                return ResourceManager.GetString("república_checa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 242.
        /// </summary>
        internal static string república_del_congo {
            get {
                return ResourceManager.GetString("república_del_congo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 243.
        /// </summary>
        internal static string república_democrática_del_congo {
            get {
                return ResourceManager.GetString("república_democrática_del_congo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 850.
        /// </summary>
        internal static string república_democrática_popular_de_corea {
            get {
                return ResourceManager.GetString("república_democrática_popular_de_corea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 856.
        /// </summary>
        internal static string república_democrática_popular_de_Laos {
            get {
                return ResourceManager.GetString("república_democrática_popular_de_Laos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 82.
        /// </summary>
        internal static string república_de_corea {
            get {
                return ResourceManager.GetString("república_de_corea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1809.
        /// </summary>
        internal static string república_dominicana {
            get {
                return ResourceManager.GetString("república_dominicana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 262.
        /// </summary>
        internal static string reunión {
            get {
                return ResourceManager.GetString("reunión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 250.
        /// </summary>
        internal static string ruanda {
            get {
                return ResourceManager.GetString("ruanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 40.
        /// </summary>
        internal static string rumanía {
            get {
                return ResourceManager.GetString("rumanía", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        internal static string rusia {
            get {
                return ResourceManager.GetString("rusia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 685.
        /// </summary>
        internal static string samoa {
            get {
                return ResourceManager.GetString("samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 684.
        /// </summary>
        internal static string samoa_americana {
            get {
                return ResourceManager.GetString("samoa_americana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 290.
        /// </summary>
        internal static string santa_elena {
            get {
                return ResourceManager.GetString("santa_elena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1869.
        /// </summary>
        internal static string santa_kitts_y_nevis {
            get {
                return ResourceManager.GetString("santa_kitts_y_nevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1758.
        /// </summary>
        internal static string santa_Lucía {
            get {
                return ResourceManager.GetString("santa_Lucía", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 239.
        /// </summary>
        internal static string santo_tomé_y_príncipe {
            get {
                return ResourceManager.GetString("santo_tomé_y_príncipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 378.
        /// </summary>
        internal static string san_marino {
            get {
                return ResourceManager.GetString("san_marino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 508.
        /// </summary>
        internal static string san_pedro_y_miquelón {
            get {
                return ResourceManager.GetString("san_pedro_y_miquelón", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1784.
        /// </summary>
        internal static string san_vincente_y_Las_granadinas {
            get {
                return ResourceManager.GetString("san_vincente_y_Las_granadinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 221.
        /// </summary>
        internal static string senegal {
            get {
                return ResourceManager.GetString("senegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 42.
        /// </summary>
        internal static string serbia_y_montenegro {
            get {
                return ResourceManager.GetString("serbia_y_montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 248.
        /// </summary>
        internal static string seychelles {
            get {
                return ResourceManager.GetString("seychelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 232.
        /// </summary>
        internal static string sierra_Leona {
            get {
                return ResourceManager.GetString("sierra_Leona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 65.
        /// </summary>
        internal static string singapur {
            get {
                return ResourceManager.GetString("singapur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 963.
        /// </summary>
        internal static string siria {
            get {
                return ResourceManager.GetString("siria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 252.
        /// </summary>
        internal static string somalia {
            get {
                return ResourceManager.GetString("somalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 94.
        /// </summary>
        internal static string sri_Lanka {
            get {
                return ResourceManager.GetString("sri_Lanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 268.
        /// </summary>
        internal static string suazilandia {
            get {
                return ResourceManager.GetString("suazilandia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 27.
        /// </summary>
        internal static string sudáfrica {
            get {
                return ResourceManager.GetString("sudáfrica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 249.
        /// </summary>
        internal static string sudán {
            get {
                return ResourceManager.GetString("sudán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 46.
        /// </summary>
        internal static string suecia {
            get {
                return ResourceManager.GetString("suecia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 41.
        /// </summary>
        internal static string suiza {
            get {
                return ResourceManager.GetString("suiza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 597.
        /// </summary>
        internal static string surinam {
            get {
                return ResourceManager.GetString("surinam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 212.
        /// </summary>
        internal static string sáhara_occidental {
            get {
                return ResourceManager.GetString("sáhara_occidental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 66.
        /// </summary>
        internal static string tailandia {
            get {
                return ResourceManager.GetString("tailandia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 886.
        /// </summary>
        internal static string taiwán {
            get {
                return ResourceManager.GetString("taiwán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 992.
        /// </summary>
        internal static string tajikistán {
            get {
                return ResourceManager.GetString("tajikistán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 255.
        /// </summary>
        internal static string tanzania {
            get {
                return ResourceManager.GetString("tanzania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 246.
        /// </summary>
        internal static string territorio_oceánico_de_la_india_británica {
            get {
                return ResourceManager.GetString("territorio_oceánico_de_la_india_británica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 670.
        /// </summary>
        internal static string timor {
            get {
                return ResourceManager.GetString("timor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 670.
        /// </summary>
        internal static string timor_Leste {
            get {
                return ResourceManager.GetString("timor_Leste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 228.
        /// </summary>
        internal static string togo {
            get {
                return ResourceManager.GetString("togo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 690.
        /// </summary>
        internal static string tokelau {
            get {
                return ResourceManager.GetString("tokelau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 676.
        /// </summary>
        internal static string tonga {
            get {
                return ResourceManager.GetString("tonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1868.
        /// </summary>
        internal static string trinidad_y_tobago {
            get {
                return ResourceManager.GetString("trinidad_y_tobago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 993.
        /// </summary>
        internal static string turkmenistán {
            get {
                return ResourceManager.GetString("turkmenistán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 90.
        /// </summary>
        internal static string turquía {
            get {
                return ResourceManager.GetString("turquía", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 688.
        /// </summary>
        internal static string tuvalu {
            get {
                return ResourceManager.GetString("tuvalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 216.
        /// </summary>
        internal static string túnez {
            get {
                return ResourceManager.GetString("túnez", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 380.
        /// </summary>
        internal static string ucrania {
            get {
                return ResourceManager.GetString("ucrania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 256.
        /// </summary>
        internal static string uganda {
            get {
                return ResourceManager.GetString("uganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 7.
        /// </summary>
        internal static string unión_sovietica {
            get {
                return ResourceManager.GetString("unión_sovietica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 598.
        /// </summary>
        internal static string uruguay {
            get {
                return ResourceManager.GetString("uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 998.
        /// </summary>
        internal static string uzbekistán {
            get {
                return ResourceManager.GetString("uzbekistán", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 678.
        /// </summary>
        internal static string vanuatu {
            get {
                return ResourceManager.GetString("vanuatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 379.
        /// </summary>
        internal static string vaticano {
            get {
                return ResourceManager.GetString("vaticano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 58.
        /// </summary>
        internal static string venezuela {
            get {
                return ResourceManager.GetString("venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 84.
        /// </summary>
        internal static string vietnam {
            get {
                return ResourceManager.GetString("vietnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 681.
        /// </summary>
        internal static string wallis_y_futuna {
            get {
                return ResourceManager.GetString("wallis_y_futuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 967.
        /// </summary>
        internal static string yemen {
            get {
                return ResourceManager.GetString("yemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 381.
        /// </summary>
        internal static string yugoslavia {
            get {
                return ResourceManager.GetString("yugoslavia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 243.
        /// </summary>
        internal static string zaire {
            get {
                return ResourceManager.GetString("zaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 260.
        /// </summary>
        internal static string zambia {
            get {
                return ResourceManager.GetString("zambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 263.
        /// </summary>
        internal static string zimbabue {
            get {
                return ResourceManager.GetString("zimbabue", resourceCulture);
            }
        }
    }
}
